# version: '3.9'

services:
  db:
    image: postgres:${POSTGRES_VERSION}
    container_name: ${PROJECT_NAME}-db
    env_file: .env.dev # Прокидываем настройки БД из dev-файла
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - tasktimer_net

  redis:
    image: redis:${REDIS_VERSION}
    container_name: ${PROJECT_NAME}-redis
    networks:
      - tasktimer_net

  mercure:
    image: dunglas/mercure:${MERCURE_VERSION}
    container_name: ${PROJECT_NAME}-mercure
    environment:
      SERVER_NAME: :80
      MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_JWT_SECRET}
      MERCURE_EXTRA_DIRECTIVES: "cors_origins *"
    ports:
      - "${MERCURE_PORT}:80"
    networks:
      - tasktimer_net

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: ${PROJECT_NAME}-backend
    env_file: .env.dev # <--- Подхватит настройки Symfony для dev
    volumes:
      - ./backend:/var/www/symfony
    networks:
      - tasktimer_net

  frontend:
    image: node:${NODE_VERSION}
    container_name: ${PROJECT_NAME}-frontend
    env_file: .env.dev
    working_dir: /src
    volumes:
      - ./frontend:/src
      - /src/.nuxt
      - /src/node_modules
    ports:
      - "3000:3000" # Проброс порта
    command: sh -c "npm install && npm run dev"
    networks:
      - tasktimer_net

  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: ${PROJECT_NAME}-nginx
    ports:
      - "${NGINX_PORT_LOCAL}:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www/symfony
    depends_on:
      - backend
      - frontend
    networks:
      - tasktimer_net

networks:
  tasktimer_net:
    driver: bridge

volumes:
  db_data: