<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260502182500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE department (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, director_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CD1DE18A899FB366 ON department (director_id)');
        $this->addSql('CREATE TABLE user_department (user_id INT NOT NULL, department_id INT NOT NULL, PRIMARY KEY (user_id, department_id))');
        $this->addSql('CREATE INDEX IDX_6A7A2766A76ED395 ON user_department (user_id)');
        $this->addSql('CREATE INDEX IDX_6A7A2766AE80F5DF ON user_department (department_id)');
        $this->addSql('ALTER TABLE department ADD CONSTRAINT FK_CD1DE18A899FB366 FOREIGN KEY (director_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_department ADD CONSTRAINT FK_6A7A2766A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_department ADD CONSTRAINT FK_6A7A2766AE80F5DF FOREIGN KEY (department_id) REFERENCES department (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE department DROP CONSTRAINT FK_CD1DE18A899FB366');
        $this->addSql('ALTER TABLE user_department DROP CONSTRAINT FK_6A7A2766A76ED395');
        $this->addSql('ALTER TABLE user_department DROP CONSTRAINT FK_6A7A2766AE80F5DF');
        $this->addSql('DROP TABLE department');
        $this->addSql('DROP TABLE user_department');
    }
}
